---
- name: Run dpkg and apt-get commands
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install veeam-release
      command: dpkg -i ./veeam-release*
      args:
        chdir: /tmp

    - name: Install blksnap and veeam
      command: apt-get install -y blksnap veeam
      args:
        chdir: /tmp

    - name: Update apt
      command: apt update
      args:
        chdir: /tmp
