- name: Install Veeam Release
  hosts: all
  become: true
  tasks:
    - name: Copy Veeam Release to /tmp
      copy:
        src: "{{ playbook_dir }}/veeam-release*"
        dest: /tmp/
    - name: Install Veeam repo
      shell: dpkg -i /tmp/veeam-release* && apt-get update
      
      - name: Install Veeam Release
      shell: apt-get install blksnap veeam
