- name: Run veeam installation
  hosts: all
  become: true
  tasks:
   - name: Install veeam package
    shell: dpkg -i /tmp/veeam-release* && apt-get update
    args:
      chdir: /tmp
  - name: Install blksnap and veeam
    apt:
      name:
        - blksnap
        - veeam
      state: present
