- name: Install Veeam
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Veeam Repository
      command: dpkg -i ./veeam-release-deb_1.0.8_amd64.deb && apt-get update
      args:
        chdir: /tmp

    - name: Install Veeam
      command: apt-get install blksnap veeam
      args:
        chdir: /tmp
