- name: Run veeam installation
  hosts: all
  become: true
   tasks:
    - name: Install Veeam Repository
      command: dpkg -i ./veeam-release* && apt-get update
      args:
        chdir: /tmp

    - name: Install Veeam
      command: apt-get install blksnap veeam
      args:
        chdir: /tmp
