---
- name: Install Veeam RPM package
  hosts: all
  become: true

  tasks:
    
    - name: Install Veeam package using rpm
      yum:
        name: /tmp/veeam-nosnap-6.0.0.1060-1.el9.x86_64.rpm
        state: present
